"""
Chainlit helper functions.

Utilities for integrating LangChain agent responses with Chainlit UI,
particularly for extracting and displaying Plotly visualizations.
"""

from typing import List, Any, Dict
import plotly.graph_objects as go


def extract_charts_from_response(agent_response: Dict[str, Any]) -> List[go.Figure]:
    """
    Extract Plotly figures from LangChain agent intermediate steps.

    Scans through agent execution steps to find tool outputs that contain
    Plotly figure objects. This allows charts generated by visualization
    tools to be displayed in the Chainlit UI.

    Args:
        agent_response: Dictionary containing agent execution results,
                       including 'intermediate_steps' with tool actions and outputs

    Returns:
        List of Plotly Figure objects found in tool outputs, empty list if none found
    """
    charts = []

    # Extract intermediate_steps from agent response
    intermediate_steps = agent_response.get("intermediate_steps", [])

    for step in intermediate_steps:
        # Each step is a tuple: (tool_action, tool_output)
        if len(step) >= 2:
            tool_action, tool_output = step[0], step[1]

            # Check if tool output is a dict with a figure
            if isinstance(tool_output, dict) and "figure" in tool_output:
                fig = tool_output["figure"]
                if isinstance(fig, go.Figure):
                    charts.append(fig)

    return charts
